[project]
dependencies = [
    "numpy>=2.1.3",
]
name = "mthe-418-number-theory-and-cryptography"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
